apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: k8s-michigan-configs
  namespace: flux-system
spec:
  interval: 1m
  url: https://github.com/john-occasionally-blogs/k8s-michigan-configs.git
  ref:
    branch: main
  secretRef:
    name: flux-github-token
