apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: pi-cluster-apps
  namespace: flux-system
spec:
  interval: 5m0s
  sourceRef:
    kind: GitRepository
    name: k8s-michigan-configs
    namespace: flux-system
  path: ./clusters/pi-cluster
  prune: true
  targetNamespace: default
